---
- name: Infrastructure Security - Firewall Management
  hosts: all
  become: yes
  # ตัวแปร firewall_action จะถูกส่งมาจาก Survey ที่คุณตั้งค่าไว้

  tasks:
    # --- กรณีเลือก enable ---
    - name: Section - Enable and Config Firewall
      when: firewall_action == "enable"
      block:
        - name: 1.1 Install Firewalld
          ansible.builtin.package:
            name: firewalld
            state: present

        - name: 1.2 Start Service
          ansible.builtin.service:
            name: firewalld
            state: started
            enabled: yes

        - name: 1.3 Allow Services and Ports
          ansible.posix.firewalld:
            service: "{{ item.svc | default(omit) }}"
            port: "{{ item.port | default(omit) }}"
            permanent: yes
            state: enabled
            immediate: yes
          loop:
            - { svc: 'http' }
            - { svc: 'ssh' }
            - { port: '10050/tcp' }