---
- name: Infrastructure Security - Firewall Management
  hosts: all
  become: yes

  tasks:
    - name: Section - Enable and Config Firewall
      block:
        - name: 1.1 Install Firewalld
          ansible.builtin.package:
            name: firewalld
            state: present

        - name: 1.2 Start Service
          ansible.builtin.service:
            name: firewalld
            state: started
            enabled: yes

        - name: 1.3 Allow Services and Ports
          ansible.posix.firewalld:
            service: "{{ item.svc | default(omit) }}"
            port: "{{ item.port | default(omit) }}"
            permanent: yes
            state: enabled
            immediate: yes
          loop:
            - { svc: 'http' }
            - { svc: 'ssh' }
            - { port: '10050/tcp' }
            - { port: '5000/tcp' } # เพิ่มอันนี้เข้าไปเพื่อให้ Ansible ช่วยคุมตัวนี้ด้วย

